annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/pilot:1.24.2
      name: pilot
    - image: dp.apps.rancher.io/containers/proxyv2:1.24.2
      name: proxyv2
    - image: dp.apps.rancher.io/containers/bci-busybox:15.6
      name: bci-busybox
apiVersion: v2
appVersion: 1.24.2
description: Helm chart for istio control plane
icon: https://apps.rancher.io/logos/istio.png
keywords:
- istio
- istiod
- istio-discovery
maintainers:
- name: SUSE LLC
  url: https://www.suse.com/
name: istiod
version: 1.24.2
