# This singleton service account aggregates reader permissions for the revisions in a given cluster
# ATM this is a singleton per cluster with Istio installed, and is not revisioned. It maybe should be,
# as otherwise compromising the token for this SA would give you access to *every* installed revision.
# Should be used for remote secret creation.
apiVersion: v1
kind: ServiceAccount
{{- with .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- $imagePullSecrets := list }}
  {{- range . }}
      {{- if kindIs "string" . }}
          {{- $imagePullSecrets = append $imagePullSecrets (dict "name" .) }}
      {{- else }}
          {{- $imagePullSecrets = append $imagePullSecrets . }}
      {{- end }}
  {{- end }}
  {{- toYaml $imagePullSecrets | nindent 2 }}
{{- end }}
metadata:
  name: istio-reader-service-account{{- if not (eq .Values.defaultRevision "default")}}-{{ .Values.defaultRevision }}{{- end }}
  namespace: {{ .Values.global.istioNamespace }}
  labels:
    app: istio-reader
    release: {{ .Release.Name }}
    app.kubernetes.io/name: "istio-reader"
    {{- include "istio.labels" . | nindent 4 }}
