annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/ztunnel:1.24.3
      name: ztunnel
apiVersion: v2
appVersion: 1.24.3
description: Helm chart for istio ztunnel components
icon: https://apps.rancher.io/logos/istio.png
keywords:
- istio-ztunnel
- istio
maintainers:
- name: SUSE LLC
  url: https://www.suse.com/
name: ztunnel
version: 1.24.3
