apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-alerting
data:
{{ (.Files.Glob "alerting/*.yaml").AsConfig | indent 2 }}
