{
 "title": "Inspection Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "cluster", "query": "local" }
  ]
 },
 "panels": [
  {
   "title": "节点 POD CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus_from=~\"$cluster_id\", container!=\"\", resource=\"cpu\"}) by (node, prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 POD Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{prometheus_from=~\"$cluster_id\", container!=\"\", resource=\"memory\"}) by (node, prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 POD CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus_from=~\"$cluster_id\", container!=\"\", resource=\"cpu\"}) by (node, prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 POD Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{prometheus_from=~\"$cluster_id\", container!=\"\", resource=\"memory\"}) by (node, prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "健康状态",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{prometheus_from=~\"$cluster_id\", condition=\"Ready\", status=\"true\"}) by (prometheus_from, node, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP 连接数（ ESTABLISHED 和 CLOSE-WAIT 状态）",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{prometheus_from=~\"$cluster_id\"}) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总进程数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "targets": [
    {
     "expr": "sum(node_procs_running{prometheus_from=~\"$cluster_id\"}) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 1 分钟的负载",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(node_load1{prometheus_from=~\"$cluster_id\"}) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 5 分钟的负载",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(node_load5{prometheus_from=~\"$cluster_id\"}) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "节点 15 分钟的负载",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(node_load15{prometheus_from=~\"$cluster_id\"}) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from, instance) / sum(node_memory_MemTotal_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from, instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from, instance) / sum(node_filesystem_size_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from, instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘的写入速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘的读取速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网络接收流量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网络发送流量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver 请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{prometheus_from=~\"$cluster_id\", job=\"apiserver\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver 请求错误状态码分布",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{prometheus_from=~\"$cluster_id\", job=\"apiserver\", code=~\"4.*|5.*\"}[5m])) by (prometheus_from, instance, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd 请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(etcd_request_duration_seconds_count{prometheus_from=~\"$cluster_id\", job=\"apiserver\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD DB Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum((etcd_mvcc_db_total_size_in_bytes{prometheus_from=~\"$cluster_id\"})) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd 主从切换次数 (24 小时内)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 49 },
   "targets": [
    {
     "expr": "irate(etcd_server_leader_changes_seen_total{prometheus_from=~\"$cluster_id\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kubelet 请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_http_requests_total{prometheus_from=~\"$cluster_id\", job=\"kubelet\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLEG 耗时",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_relist_duration_seconds_sum{prometheus_from=~\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PLEG 丢弃事件",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(kubelet_pleg_discard_events{prometheus_from=~\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ICMP Ping 丢包率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(probe_success{job=\"blackbox-nodes\", prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP Ping 响应时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(probe_duration_seconds{job=\"blackbox-nodes\", prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from, instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}