{
 "title": "Inspection Resources",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "cluster", "query": "local" }
  ]
 },
 "panels": [
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "应用(POD)的CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{prometheus_from=~\"$cluster_id\",container!=\"\",container!=\"POD\"}[5m])) by (container, pod, namespace, prometheus_from) / (sum(container_spec_cpu_quota{prometheus_from=~\"$cluster_id\",container!=\"\",container!=\"POD\"}/100000) by (container, pod, namespace, prometheus_from)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用(POD)的内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{prometheus_from=~\"$cluster_id\",container!=\"\", container!=\"POD\", container!~\"sandbox|tcss\"}) by (prometheus_from, container, pod, namespace)\n/\nsum(container_spec_memory_limit_bytes{prometheus_from=~\"$cluster_id\",container!=\"\",container!=\"POD\",container!~\"sandbox|tcss\"}) by (prometheus_from, container, pod, namespace) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用磁盘使用大小",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{prometheus_from=~\"$cluster_id\",container!=\"\",container!=\"POD\"}) by (prometheus_from, pod, namespace)  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用重启次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(kube_pod_container_status_restarts_total{prometheus_from=\"$cluster_id\",container!=\"\"}[24h])) by (prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用运行状态为 Not Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_status_ready{prometheus_from=\"$cluster_id\", condition=\"false\"}) by (prometheus_from, pod, namespace) * on (namespace, pod) group_left(created_by_kind, created_by_name) kube_pod_info{prometheus_from=\"$cluster_id\",created_by_kind!=\"Job\"}) by (prometheus_from, namespace, created_by_kind, created_by_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用运行状态为 Pod Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(sum(kube_pod_status_phase{prometheus_from=~\"$cluster_id\", phase=~\"Failed|Pending|Unknown\"}) by (prometheus_from, pod, namespace) * on (namespace, pod) group_left(created_by_kind, created_by_name) kube_pod_info{prometheus_from=\"$cluster_id\",created_by_kind!=\"Job\"}) by (prometheus_from, namespace, created_by_kind, created_by_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用的网络传输速率（流入方向）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{prometheus_from=~\"$cluster_id\",container!=\"\"}[5m])) by (prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "应用的网络传输速率（流出方向）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{prometheus_from=~\"$cluster_id\",container!=\"\"}[5m])) by (prometheus_from, pod, namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "ingress 请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{prometheus_from=~\"$cluster_id\"}[5m])) by (prometheus_from, ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress 总请求量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_sum{prometheus_from=~\"$cluster_id\"}[5m])) by (prometheus_from, ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress 总响应量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_response_size_sum{prometheus_from=~\"$cluster_id\"}[5m])) by (prometheus_from, ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Pending\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Released",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Failed\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "PVC 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim, prometheus_from) ) / (sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim, prometheus_from) ) * 100",
     "legendFormat": "{{exported_namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "PVC 状态",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{prometheus_from=~\"$cluster_id\"}"
    },
    {
     "expr": " 1 - count(kube_persistentvolumeclaim_info{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) + count(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) / sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}