{{- /*
Copyright (c) 2025 SUSE LLC All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- $apiKey := .Values.apiKey | required ".Values.apiKey is required." -}}
{{- $apiToken := .Values.apiToken | required ".Values.apiToken is required." -}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "suse-ai-observability-extension.fullname" . }}-secret
  labels:
    {{- include "suse-ai-observability-extension.labels" . | nindent 4 }}
type: Opaque
data:
  API_KEY: {{ $apiKey | b64enc }}
  API_TOKEN: {{ $apiToken | b64enc }}