{{- /*
Copyright (c) 2025 SUSE LLC All Rights Reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "suse-ai-observability-extension.serviceAccountName" . }}
  labels:
    {{- include "suse-ai-observability-extension.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
