apiVersion: v2
appVersion: v0.1.0
dependencies:
- name: common
  repository: file://../common/
  version: '*'
description: The StackState Kafka upgrade operator
home: https://gitlab.com/StackVista/platform/kafkaup-operator
maintainers:
- email: bschuur@stackstate.com
  name: Bram Schuur
name: kafkaup-operator
version: 0.1.8
