{
 "title": "Inspection Resources",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "cluster", "query": "rke1" }
  ]
 },
 "panels": [
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ingress 请求速率",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{prometheus_from=~\"$cluster_id\"}[5m])) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress 总请求量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_size_sum{prometheus_from=~\"$cluster_id\"}[5m])) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ingress 总响应量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_response_size_sum{prometheus_from=~\"$cluster_id\"}[5m])) by (ingress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Pending\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Available\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Bound\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Released",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Released\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_status_phase{phase=\"Failed\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Pending\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Bound",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Bound\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{phase=\"Lost\", prometheus_from=~\"$cluster_id\"})"
    }
   ]
  },
  {
   "title": "PVC 使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim, prometheus_from) ) / (sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim, prometheus_from) ) * 100",
     "legendFormat": "{{exported_namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  {
   "title": "PVC 状态",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_persistentvolumeclaim_info{prometheus_from=~\"$cluster_id\"}"
    },
    {
     "expr": " 1 - count(kube_persistentvolumeclaim_info{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) + count(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) / sum(kubelet_volume_stats_capacity_bytes{prometheus_from=~\"$cluster_id\"}) by (persistentvolumeclaim,prometheus_from) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}