{
 "title": "Inspection Clusters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_id", "label": "cluster", "query": "local" }
  ]
 },
 "panels": [
  {
   "title": "CPU 使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\", prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemAvailable_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from) / sum(node_memory_MemTotal_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "证书过期倒计时",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{prometheus_from=\"$cluster_id\",instance=\"https://kubernetes.default.svc:443\"}-time()"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(node_filesystem_free_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from) / sum(node_filesystem_size_bytes{prometheus_from=\"$cluster_id\"}) by (prometheus_from)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘的写入速率",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_writes_completed_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "磁盘的读取速率 ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_reads_completed_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总网络接收流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总网络发送流量",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{prometheus_from=\"$cluster_id\"}[5m])) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calico IP 池使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(ipam_allocations_in_use{prometheus_from=\"$cluster_id\", ippool=\"default-ipv4-ippool\"}) by (prometheus_from, ippool)) / (sum(ipam_ippool_size{prometheus_from=\"$cluster_id\", ippool=\"default-ipv4-ippool\"}) by (prometheus_from, ippool)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cilium IP 池使用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{prometheus_from=\"$cluster_id\", job=\"cilium-agent\"}) by (prometheus_from)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}